### PR TITLE
Add support for Python 3.9, drop support for Python 3.5

### PR DESCRIPTION
**Pull request by jugmac00**
Also, try to fix pypy on Travis.

modified:   .travis.yml
modified:   CHANGES.rst
modified:   setup.py
modified:   tox.ini

### CODE REVIEW

**Review by dataflake — CHANGES_REQUESTED** [review]
You cannot drop Python 3.5, this package is needed for Zope 4. The same policy that applies to Python 2 applies here. Please see https://www.zope.org/developer/development-culture.html#python-2-support-policy

**Comment by jugmac00** [comment]
In Zope's changelog you can read "Drop `ZopeUndo` dependency." - This was three years ago.

But nevermind, I add it back again. Thanks for the hint!

**Comment by dataflake** [comment]
> In Zope's changelog you can read "Drop `ZopeUndo` dependency." - This was three years ago.

Oh, yes, you are right. Sorry for the noise. Now I wonder what this package is used for at all...

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
According to the README: "This package is included in Zope 2. It can be used in a ZEO server to allow it to support Zope 2's undo log , without pulling in all of Zope 2."
But it is only used there for a regression test.

**Pull request merged**
